services:
  monitor:
    container_name: watchcat
    labels:
      - monitoring
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
